doctrine:
  orm:
    mappings:
      CarguruMemberBundle:
        type: annotation
        dir: '/Model'
        is_bundle: true
        prefix: Carguru\MemberBundle\Model

security:
  providers:
    members:
      entity: { class: Carguru\MemberBundle\Model\Member, property: username }

  access_decision_manager:
    strategy: unanimous

  firewalls:
    admin:
      pattern: /admin(.*)
      lazy: true
      provider: members
      custom_authenticators:
        - Carguru\MemberBundle\Security\MemberFormAuthenticator
      logout:
        path: carguru_member_logout
        target: carguru_member_login
        invalidate_session: true
      remember_me:
        secret: '%kernel.secret%'
        name: 'carguru_member_rememberme_cookie'
        lifetime: 3600
        path: /admin
        httponly: true

  role_hierarchy:
    ROLE_ADMIN: [ ROLE_USER, ROLE_SONATA_ADMIN ]
    ROLE_SUPER_ADMIN: [ ROLE_ADMIN, ROLE_ALLOWED_TO_SWITCH ]
    SONATA:
      - ROLE_SONATA_PAGE_ADMIN_PAGE_EDIT